import { decodeAdapterBytes, displayName, normalizeEvent, objectRecord, readSessionRecords, type SessionRecord } from "./common.js";
import { lookupTopologyCapability } from "./topology.js";
import { MalformedAdapterInputError, normalizeAdapterInput, singleAdapterPart, type AdapterInput, type AdapterManifest, type AdapterRecord, type TraceAdapter } from "./types.js";
function str(value: unknown): string | null { return typeof value === "string" && value.length > 0 ? value : null; }
function jsonPart(path: string, bytes: Uint8Array): Record<string, unknown> | null { try { return objectRecord(JSON.parse(decodeAdapterBytes(bytes))); } catch { return null; } }
function rootOf(id: string, parents: Map<string, string | null>): string { const seen = new Set<string>(); let current = id; while (!seen.has(current)) { seen.add(current); const parent = parents.get(current); if (!parent || parent === current) break; current = parent; } return current; }
export class GrokSessionAdapter implements TraceAdapter {
  readonly manifest: AdapterManifest = { source: "grok", adapterVersion: "1.0.0", supportedFormatVersions: ["grok-session-v1"], status: "implemented", topology: lookupTopologyCapability("grok", "1.0.0") };
  async sniff(input: AdapterInput): Promise<boolean> { try { return /updates\.jsonl$/iu.test(singleAdapterPart(input).path); } catch { return false; } }
  async *parse(input: AdapterInput): AsyncIterable<AdapterRecord> {
    const normalized = normalizeAdapterInput(input); const sessions = new Map<string, { path: string; records: SessionRecord[] }>(); const parents = new Map<string, string | null>(); const spawnFacts: Array<{ parent: string; child: string; prompt: string | null }> = []; const joins = new Set<string>();
    try {
      for (const part of normalized.parts) {
        if (part.path.endsWith(".lock")) continue;
        if (part.path.endsWith("updates.jsonl")) { const records = readSessionRecords(decodeAdapterBytes(part.bytes)); const id = part.path.includes("parent/") ? "grok-root" : part.path.includes("child/") ? "grok-child" : part.path.split("/").at(-2) ?? part.path; sessions.set(id, { path: part.path, records }); parents.set(id, null); }
        if (part.path.endsWith("meta.json")) { const object = jsonPart(part.path, part.bytes); const child = str(object?.child_session_id ?? object?.subagent_id); const parent = str(object?.parent_session_id); if (child) parents.set(child, parent); }
        if (part.path.endsWith("output.json")) { const object = jsonPart(part.path, part.bytes); const child = part.path.split("/").at(-2); if (child && object) joins.add(child); }
      }
      for (const session of sessions.values()) for (const record of session.records) { const object = objectRecord(record.value); const params = objectRecord(object?.params); const update = objectRecord(params?.update); if (String(update?.sessionUpdate) === "subagent_spawned") { const parent = str(params?.sessionId); const child = str(update?.child_session_id ?? update?.subagent_id); if (parent && child) { parents.set(child, parent); spawnFacts.push({ parent, child, prompt: str(update?.parent_prompt_id) }); } } if (String(update?.sessionUpdate) === "subagent_finished") { const child = str(update?.child_session_id ?? update?.subagent_id); if (child) joins.add(child); } }
    } catch (error) { throw new MalformedAdapterInputError("grok", String(error)); }
    const traces = new Map<string, string>(); for (const id of sessions.keys()) traces.set(id, rootOf(id, parents)); const spawnByChild = new Map(spawnFacts.map((fact) => [fact.child, fact]));
    for (const [id, session] of sessions) { const lane = id; const trace = traces.get(id) ?? rootOf(id, parents); for (const record of session.records) { const object = objectRecord(record.value); const params = objectRecord(object?.params); const update = objectRecord(params?.update); if (!object || !update || String(update.sessionUpdate) === "agent_thought_chunk") continue; const eventId = str(object._meta && objectRecord(object._meta)?.eventId) ?? `${id}-${record.line}`; const attrs: Record<string, unknown> = { recordType: String(update.sessionUpdate ?? object.method ?? "update") }; const spawn = spawnByChild.get(id); if (spawn) { attrs.parentAgentId = rootOf(spawn.parent, parents); attrs.topologyProvenance = "stated"; } if (joins.has(id)) { attrs.joinedBy = id; attrs.joinedAgentIds = [id]; } const event = normalizeEvent({ source: "grok", formatVersion: "grok-session-v1", adapterVersion: this.manifest.adapterVersion, sourceIdentity: input.sourceIdentity, sessionId: `${trace}@${this.manifest.adapterVersion}`, line: record.line }, { sourceEventId: eventId, occurredAt: typeof object.timestamp === "string" ? new Date(Number(object.timestamp) * 1000).toISOString() : undefined, kind: String(update.sessionUpdate) === "subagent_finished" ? "tool_result" : String(update.sessionUpdate) === "subagent_spawned" ? "tool_call" : "log", name: displayName(`Grok ${id}`, update.content ?? update.output ?? update.sessionUpdate), status: "ok", agentId: lane, parentSpanId: spawn?.prompt ?? undefined, attributes: attrs, payload: object, traceTitle: "Grok session" }); yield { type: "event", event }; yield { type: "artifact", key: `event-${eventId}`, sourceEventId: eventId, bytes: new TextEncoder().encode(JSON.stringify(object)), mediaType: "application/json" }; } }
  }
  }
