import type { RawEventKind } from "@intenttrace/schema";
import { decodeAdapterBytes, displayName, normalizeEvent, objectRecord, readSessionRecords, type SessionRecord } from "./common.js";
import { lookupTopologyCapability } from "./topology.js";
import { MalformedAdapterInputError, normalizeAdapterInput, singleAdapterPart, type AdapterInput, type AdapterManifest, type AdapterRecord, type TraceAdapter } from "./types.js";
function str(value: unknown): string | null { return typeof value === "string" && value.length > 0 ? value : null; }
function kind(value: Record<string, unknown>): RawEventKind { if (value.type === "session") return "agent_start"; if (value.type === "message") return "assistant_message"; if (value.type === "custom_message") return "tool_result"; return "log"; }
function titlePath(path: string): string { return path.split("/").at(-1)?.replace(/\.jsonl$/iu, "") || "Main"; }
interface OmpPart { path: string; lane: string; records: SessionRecord[] }
export class OmpSessionAdapter implements TraceAdapter {
  readonly manifest: AdapterManifest = { source: "omp", adapterVersion: "1.0.0", supportedFormatVersions: ["omp-jsonl-v1"], status: "implemented", topology: lookupTopologyCapability("omp", "1.0.0") };
  async sniff(input: AdapterInput): Promise<boolean> { try { return objectRecord(readSessionRecords(decodeAdapterBytes(singleAdapterPart(input).bytes))[1]?.value)?.type === "session"; } catch { return false; } }
  async *parse(input: AdapterInput): AsyncIterable<AdapterRecord> {
    const normalized = normalizeAdapterInput(input); const root = normalized.parts.find((part) => !part.path.includes("/")); if (!root) throw new MalformedAdapterInputError("omp", "bundle requires root session file");
    const rootId = str(objectRecord(readSessionRecords(decodeAdapterBytes(root.bytes))[1]?.value)?.id) ?? root.path; const parts: OmpPart[] = [];
    for (const part of normalized.parts) { let records: SessionRecord[]; try { records = readSessionRecords(decodeAdapterBytes(part.bytes)); } catch (error) { throw new MalformedAdapterInputError("omp", String(error)); } parts.push({ path: part.path, lane: part.path === root.path ? "Main" : titlePath(part.path), records: records.slice(1) }); }
    const children = new Set<string>(parts.filter((part) => part.lane !== "Main").map((part) => part.lane)); const joins = new Set<string>(); const peers = new Map<string, { from: string; to: string }>();
    for (const part of parts) for (const record of part.records) { const object = objectRecord(record.value); if (!object) continue; const details = objectRecord(object.details) ?? objectRecord(objectRecord(object.message)?.details); const jobs = Array.isArray(details?.jobs) ? details.jobs : []; for (const item of jobs) { const id = str(objectRecord(item)?.id ?? objectRecord(item)?.jobId); if (id) joins.add(id); } const waited = objectRecord(details?.waited); const from = str(waited?.from) ?? str(details?.from); const to = str(waited?.to); if (from && to) peers.set(str(waited?.id) ?? `${from}-${to}-${record.line}`, { from, to }); }
    for (const part of parts) for (const record of part.records) { const object = objectRecord(record.value); if (!object) continue; const eventId = str(object.id) ?? `${part.lane}-${record.line}`; const attrs: Record<string, unknown> = { recordType: String(object.type ?? "unknown") }; if (part.lane !== "Main" && children.has(part.lane)) { attrs.parentAgentId = "Main"; attrs.topologyProvenance = "inferred"; } if (joins.has(part.lane)) { attrs.joinedBy = part.lane; attrs.joinedAgentIds = [part.lane]; } const peer = [...peers.entries()].find(([, value]) => value.from === part.lane || value.to === part.lane); if (peer) { attrs.senderAgentId = peer[1].from; attrs.recipientAgentId = peer[1].to; attrs.messageId = peer[0]; } const event = normalizeEvent({ source: "omp", formatVersion: "omp-jsonl-v1", adapterVersion: this.manifest.adapterVersion, sourceIdentity: input.sourceIdentity, sessionId: `${rootId}@${this.manifest.adapterVersion}`, line: record.line }, { sourceEventId: eventId, occurredAt: typeof object.timestamp === "string" ? object.timestamp : undefined, kind: kind(object), name: displayName(`OMP ${part.lane}`, object.message ?? object.customType ?? object.type), status: "ok", agentId: part.lane, spanId: str(object.id) ?? undefined, attributes: attrs, payload: object, traceTitle: "OMP session" }); yield { type: "event", event }; yield { type: "artifact", key: `event-${eventId}`, sourceEventId: eventId, bytes: new TextEncoder().encode(JSON.stringify(object)), mediaType: "application/json" }; }
  }
}
